spring:
  elasticsearch:
    properties:
      path:
        home: /Users/larrymitchell/teamgannon/terranrepublicviewer/datadir

security:
  user:
    name: Caine
    password: Mutiny
  basic:
    enabled: true

server:
  port: 9100
  contextPath: /admin

management:
  context-path: /manage
  security:
    enabled: true

info:
  app:
    name: terranrepublicviewer
    description: The Terran Republic Viewer
    version: 0.1
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: 1.0.0
    version: ${project.version}